### ISSUE TITLE
error pushing

### ISSUE THREAD

**Issue by yuchenzhang10** [MIDS-INFO-W18/Installation#2]
when i git push my file i get this error below?

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	Installation/

MacBook-Pro:assignment-upstream-summer17 yuchen$ git commit -m "completed GitHub exercise".
[master 7d60c9c] completed GitHub exercise.
 1 file changed, 18 insertions(+)
 create mode 100644 submissions/first_github_exercise.txt
MacBook-Pro:assignment-upstream-summer17 yuchen$ git status
On branch master
Untracked files:
  (use "git add <file>..." to include in what will be committed)

	Installation/

nothing added to commit but untracked files present (use "git add" to track)
MacBook-Pro:assignment-upstream-summer17 yuchen$ git push origin master
To https://github.com/MIDS-INFO-W18/YuchenZhangREPO.git
 ! [rejected]        master -> master (fetch first)
error: failed to push some refs to 'https://github.com/MIDS-INFO-W18/YuchenZhangREPO.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.

**Comment by rrdkent** [comment]
Have you added the SUBMISSIONS folder?  can you run `git status` and paste what you see?

**Comment by gunnarklee** [comment]
Yuchen

Where you able to resolve this one. It looks like you have successfully
pushed to your "submissions" folder which is good. The problem seems to be
related to the "installation" folder that is on the YuchenZhangREPO but not
on the original "assignments-upstream" and likely not on your local
assignments-upstream anymore. Can you pull from the original repo then "git
add ." add all changes and see If you can push again. We may have to sit
down with this one on one to fix it up.

-Gunnar
